require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/environments/*'

# Allowing a bit more length for modern wide screens
Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true

# RSpec specific configurations
RSpec/MultipleExpectations:
  Max: 5

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'